#!/bin/bash
if [ -z "$2" ]
then
	PATH=127.0.0.1:2001/scriptresponse/bodysize_response.php
else
	PATH=$2
fi
if [ -z "$1" ]
then
	SIZE=10
else
	SIZE=$1
fi

echo "Bodysize $SIZE"

echo "test with 8"
/usr/bin/curl -X POST -H "Content-Type: plain/text" --data "BODYSIZE" $PATH

echo "test with 9"
/usr/bin/curl -X POST -H "Content-Type: plain/text" --data "BODYSIZE9" $PATH

echo "test with 10"
/usr/bin/curl -X POST -H "Content-Type: plain/text" --data "BODYSIZE10" $PATH

echo "test with 11"
/usr/bin/curl -X POST -H "Content-Type: plain/text" --data "BODYSIZE910" $PATH